# nome, marca_cod, marca, segmento, regex_inclui, regex_exclui
FAMILIES = [
 ("Chevrolet Onix",        23,"Chevrolet","Hatch compacto",   r'^ONIX HATCH', None),
 ("Hyundai HB20",          26,"Hyundai",  "Hatch compacto",   r'^HB20\b', r'HB20S|HB20X'),
 ("VW Polo",               59,"VW",       "Hatch compacto",   r'^Polo\b', None),
 ("Fiat Argo",             21,"Fiat",     "Hatch compacto",   r'^ARGO\b', None),
 ("Toyota Yaris Hatch",    56,"Toyota",   "Hatch compacto",   r'^YARIS\b', r'Sed|Cross|GR '),
 ("Honda City Hatch",      25,"Honda",    "Hatch compacto",   r'^CITY Hatchback', None),
 ("Renault Sandero",       48,"Renault",  "Hatch compacto",   r'^SANDERO', None),
 ("Honda Fit",             25,"Honda",    "Hatch compacto",   r'^Fit\b', None),
 ("Toyota Etios Hatch",    56,"Toyota",   "Hatch compacto",   r'^ETIOS\b', r'Sed'),
 ("Chevrolet Onix Plus",   23,"Chevrolet","Sedan compacto",   r'^ONIX (SED|SD)', None),
 ("VW Virtus",             59,"VW",       "Sedan compacto",   r'^VIRTUS', None),
 ("Hyundai HB20S",         26,"Hyundai",  "Sedan compacto",   r'^HB20S', None),
 ("Fiat Cronos",           21,"Fiat",     "Sedan compacto",   r'^CRONOS', None),
 ("Toyota Yaris Sedan",    56,"Toyota",   "Sedan compacto",   r'^YARIS.*Sed', None),
 ("Nissan Versa",          43,"Nissan",   "Sedan compacto",   r'^VERSA', None),
 ("Honda City Sedan",      25,"Honda",    "Sedan compacto",   r'^CITY Sedan', None),
 ("Chevrolet Prisma",      23,"Chevrolet","Sedan compacto",   r'^PRISMA', None),
 ("Renault Logan",         48,"Renault",  "Sedan compacto",   r'^LOGAN', None),
 ("Chevrolet Tracker",     23,"Chevrolet","SUV compacto",     r'^TRACKER', None),
 ("Hyundai Creta",         26,"Hyundai",  "SUV compacto",     r'^Creta', None),
 ("VW T-Cross",            59,"VW",       "SUV compacto",     r'^T-Cross', None),
 ("VW Nivus",              59,"VW",       "SUV compacto",     r'^Nivus', None),
 ("Fiat Pulse",            21,"Fiat",     "SUV compacto",     r'^PULSE', None),
 ("Fiat Fastback",         21,"Fiat",     "SUV compacto",     r'^Fastback', None),
 ("Jeep Renegade",         29,"Jeep",     "SUV compacto",     r'^Renegade', None),
 ("Nissan Kicks",          43,"Nissan",   "SUV compacto",     r'^KICKS', None),
 ("Renault Duster",        48,"Renault",  "SUV compacto",     r'^DUSTER', r'OROCH'),
 ("Renault Captur",        48,"Renault",  "SUV compacto",     r'^CAPTUR', None),
 ("Honda HR-V",            25,"Honda",    "SUV compacto",     r'^HR-V', None),
 ("Honda WR-V",            25,"Honda",    "SUV compacto",     r'^WR-V', None),
 ("Hyundai HB20X",         26,"Hyundai",  "SUV compacto",     r'^HB20X', None),
 ("Toyota Corolla",        56,"Toyota",   "Sedan medio",      r'^Corolla\b', r'Cross|Fielder'),
 ("Toyota Corolla Cross",  56,"Toyota",   "SUV medio",        r'^Corolla Cross', None),
 ("Honda Civic",           25,"Honda",    "Sedan medio",      r'^Civic Sed', None),
 ("Chevrolet Cruze",       23,"Chevrolet","Sedan medio",      r'^CRUZE', None),
 ("Jeep Compass",          29,"Jeep",     "SUV medio",        r'^COMPASS', None),
 ("VW Jetta",              59,"VW",       "Sedan medio",      r'^JETTA', None),
 ("Nissan Sentra",         43,"Nissan",   "Sedan medio",      r'^Sentra', None),
 ("Chevrolet Spin",        23,"Chevrolet","Monovolume 7L",    r'^SPIN', None),
]
